In [1]:
import pandas as pd

In [2]:
df_internet = pd.read_csv("../data/raw/internet_users_dataset.csv", skiprows=4)

In [3]:
df_turkey = df_internet[df_internet["Country Name"].str.contains("Tur", case=False)]
df_turkey.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
228,Turks and Caicos Islands,TCA,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Turkmenistan,TKM,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Turkiye,TUR,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.684618,71.042761,73.976702,77.669561,81.408437,83.437166,85.960742,87.307877,89.77024,NaN

In [4]:
df_internet['Indicator Name'].unique()

<StringArray>
['Individuals using the Internet (% of population)']
Length: 1, dtype: str

In [5]:
df_turkey[["Country Name", "2015", "2016", "2017", "2018", "2019", "2020"]]

,Country Name,2015,2016,2017,2018,2019,2020
228,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN
235,Turkmenistan,14.996800,17.990299,NaN,NaN,NaN,NaN
244,Turkiye,53.744979,58.347734,64.684618,71.042761,73.976702,77.669561

In [6]:
df_internet.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              266
                 ...
2022               51
2023               52
2024               51
2025              223
Unnamed: 70       266
Length: 71, dtype: int64

In [7]:
countries =  ["United States", "Germany", "Brazil", "Turkiye", "Thailand", "Viet Nam", "Canada", "United Kingdom", "Japan", "India"]

df_internet = df_internet[df_internet['Country Name'].isin(countries)]

df_internet["Country Name"] = df_internet["Country Name"].replace({
    "Viet Nam": "Vietnam", "Turkiye": "Turkey"
})

In [8]:
df_internet['Country Name'].unique()

<StringArray>
[        'Brazil',         'Canada',        'Germany', 'United Kingdom',
          'India',          'Japan',       'Thailand',         'Turkey',
  'United States',        'Vietnam']
Length: 10, dtype: str

In [9]:
df_internet.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
29,Brazil,BRA,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.471285,70.434283,73.912440,81.342694,80.689893,80.527751,84.150602,84.463472,NaN,NaN
35,Canada,CAN,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.701401,94.640000,91.912903,92.300000,93.937103,94.000000,94.145302,94.353302,NaN,NaN
55,Germany,DEU,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,84.394154,87.037112,88.134517,89.812941,91.430610,91.629844,92.476376,93.499996,NaN,NaN
81,United Kingdom,GBR,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,90.424550,90.692009,92.516629,94.818201,96.196503,95.465302,95.447197,95.472099,NaN,NaN
109,India,IND,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.200001,20.081300,29.523500,43.405443,49.258099,55.900000,60.252300,64.943497,70.0,NaN

In [10]:
df_internet['internet_users'] = df_internet[['2016', '2017']].mean(axis=1)

In [11]:
df_internet = df_internet[['Country Name', 'internet_users', "Country Code"]]

In [12]:
df_internet.columns = ['country', 'internet_users', 'country_code']

In [13]:
df_internet['country'] = df_internet['country'].str.strip()

In [14]:
df_internet = df_internet.reset_index(drop=True)
df_internet.head(10)

          country  internet_users country_code
0          Brazil       64.171912          BRA
1          Canada       91.930702          CAN
2         Germany       84.279680          DEU
3  United Kingdom       92.600176          GBR
4           India       17.350000          IND
5           Japan       92.454634          JPN
6        Thailand       50.198447          THA
7          Turkey       61.516176          TUR
8   United States       86.409655          USA
9         Vietnam       55.570000          VNM

In [18]:
df_internet.rename(columns={'internet_users': 'avg_internet_usage_pct'}, inplace=True)

In [19]:
df_internet['avg_internet_usage_pct'] = df_internet['avg_internet_usage_pct'].round(2)

In [20]:
df_internet.dtypes

country                       str
avg_internet_usage_pct    float64
country_code                  str
dtype: object

In [22]:
df_internet.head()

          country  avg_internet_usage_pct country_code
0          Brazil                   64.17          BRA
1          Canada                   91.93          CAN
2         Germany                   84.28          DEU
3  United Kingdom                   92.60          GBR
4           India                   17.35          IND

In [21]:
df_internet.to_csv("../data/processed/internet_clean.csv", index=False)