"Fixed broadband subscriptions (per 100 people)"

"Fixed broadband subscriptions refers to fixed subscriptions to high-speed access to the public Internet (a TCP/IP connection), at downstream speeds equal to, or greater than, 256 kbit/s. This includes cable modem, DSL, fiber-to-the-home/building, other fixed (wired)-broadband subscriptions, satellite broadband and terrestrial fixed wireless broadband. This total is measured irrespective of the method of payment. It excludes subscriptions that have access to data communications (including the Internet) via mobile-cellular networks. It should include fixed WiMAX and any other fixed wireless technologies. It includes both residential subscriptions and subscriptions for organizations.","World Telecommunication/ICT Indicators Database, International Telecommunication Union (ITU)",

In [26]:
import pandas as pd

In [27]:
df_fixed_broadband = pd.read_csv("../data/raw/fixed_broadband_subscriptions.csv", skiprows=4)

In [28]:
countries =  ["United States", "Germany", "Brazil", "Turkiye", "Thailand", "Viet Nam", "Canada", "United Kingdom", "Japan", "India"]

df_fixed_broadband = df_fixed_broadband[df_fixed_broadband['Country Name'].isin(countries)]

df_fixed_broadband["Country Name"] = df_fixed_broadband["Country Name"].replace({
    "Viet Nam": "Vietnam", "Turkiye": "Turkey"})

In [29]:
df_fixed_broadband['broadband'] = df_fixed_broadband[['2016', '2017']].mean(axis=1)

df_fixed_broadband = df_fixed_broadband[['Country Name', 'broadband', "Country Code"]]
df_fixed_broadband.columns = ['country', 'broadband', 'country_code']

In [30]:
df_fixed_broadband.rename(columns={
    'broadband': 'fixed_broadband_subscriptions_per_100_people'
}, inplace=True)

In [31]:
df_fixed_broadband = df_fixed_broadband.reset_index(drop=True)
df_fixed_broadband.head(10)

          country  fixed_broadband_subscriptions_per_100_people country_code
0          Brazil                                     13.669768          BRA
1          Canada                                     37.325490          CAN
2         Germany                                     39.243956          DEU
3  United Kingdom                                     38.953902          GBR
4           India                                      1.350613          IND
5           Japan                                     31.601317          JPN
6        Thailand                                     10.861128          THA
7          Turkey                                     13.605975          TUR
8   United States                                     32.342342          USA
9         Vietnam                                     10.760025          VNM

In [33]:
df_fixed_broadband['fixed_broadband_subscriptions_per_100_people'] = (
    df_fixed_broadband['fixed_broadband_subscriptions_per_100_people'].round(2)
)

In [34]:
df_fixed_broadband.dtypes

country                                             str
fixed_broadband_subscriptions_per_100_people    float64
country_code                                        str
dtype: object

In [35]:
df_fixed_broadband.head()

          country  fixed_broadband_subscriptions_per_100_people country_code
0          Brazil                                         13.67          BRA
1          Canada                                         37.33          CAN
2         Germany                                         39.24          DEU
3  United Kingdom                                         38.95          GBR
4           India                                          1.35          IND

In [36]:
df_fixed_broadband.to_csv("../data/processed/fixed_broadband_clean.csv", index=False)