In [1]:
import pandas as pd

In [ ]:
df_india = pd.read_csv("../data/raw/weather_data_india.csv")
print(df_india.isnull().sum())
df_india['country'] ='India' #raw data does not have a column named "country" 
print(df_india.columns)
print(df_india)
df_india.to_csv("../data/processed/india_clean.csv", index=False)

date                   0
temperature_2m_mean    0
temperature_2m_max     0
temperature_2m_min     0
wind_speed_10m_max     0
precipitation_sum      0
rain_sum               0
snowfall_sum           0
precipitation_hours    0
wind_gusts_10m_max     0
daylight_duration      0
sunshine_duration      0
sunset                 0
sunrise                0
dtype: int64
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')
                          date  temperature_2m_mean  temperature_2m_max  \
0    2016-07-31 00:00:00+00:00            25.539420             27.4415
1    2016-08-01 00:00:00+00:00            24.831080             25.8415
2    2016-08-02 00:00:00+00:00            24.545668             26.0915
3    2016-08-03 00:00:00+00:00            24.343584             24.6915
4    2016-08-04 00:00:00+00:00            25.264418             27.6415
..                         ...                  ...                 ...
362  2017-07-28 00:00:00+00:00            26.316668             29.9000
363  2017-07-29 00:00:00+00:00            27.779167             31.2000
364  2017-07-30 00:00:00+00:00            28.154165             31.6000
365  2017-07-31 00:00:00+00:00            28.527086             31.8500
366  2017-08-01 00:00:00+00:00            29.112501             32.6500

     temperature_2m_min  wind_speed_10m_max  precipitation_sum   rain_sum  \
0             24.291500           12.287555           5.800000   5.800000
1             23.841500           19.665360          11.700001  11.700001
2             23.241499           21.129883          31.100006  31.100006
3             23.941500           18.947083          24.700000  24.700000
4             23.691500           17.015474          22.800001  22.800001
..                  ...                 ...                ...        ...
362           23.900000           20.265795           1.300000   1.300000
363           24.150000           18.359999           0.800000   0.800000
364           25.350000           18.486622           0.200000   0.200000
365           25.650000           16.935310           0.200000   0.200000
366           25.950000           16.750640           0.000000   0.000000

     snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0             0.0                 21.0           25.919998          47028.867
1             0.0                 19.0           39.960000          46978.285
2             0.0                 20.0           40.320000          46927.080
3             0.0                 19.0           44.639996          46874.836
4             0.0                 16.0           47.880000          46821.540
..            ...                  ...                 ...                ...
362           0.0                  7.0           47.519997          47191.348
363           0.0                  6.0           34.560000          47143.457
364           0.0                  2.0           35.640000          47094.400
365           0.0                  2.0           37.079998          47044.234
366           0.0                  0.0           36.719997          46993.020

     sunshine_duration      sunset     sunrise country
0            4190.7573  1469971357  1469924317   India
1               0.0000  1470057728  1470010739   India
2               0.0000  1470144099  1470097160   India
3               0.0000  1470230468  1470183581   India
4            4311.6880  1470316836  1470270002   India
..                 ...         ...         ...     ...
362         26502.5660  1501248247  1501201045   India
363         42953.1400  1501334621  1501287467   India
364         34608.3320  1501420994  1501373889   India
365         43192.8950  1501507366  1501460311   India
366         43200.0000  1501593737  1501546733   India

[367 rows x 15 columns]

In [7]:
df_uk = pd.read_csv("../data/raw/weather_data_uk.csv")
df_uk['country'] = "United Kingdom"
print(df_uk.head())
print(df_uk.columns)
df_uk.to_csv("../data/processed/uk_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            11.263667           14.109500
1  2016-08-01 00:00:00+00:00            11.719917           15.109500
2  2016-08-02 00:00:00+00:00            12.930332           16.109499
3  2016-08-03 00:00:00+00:00            13.540751           14.709500
4  2016-08-04 00:00:00+00:00            14.015750           16.509500

   temperature_2m_min  wind_speed_10m_max  wind_gusts_10m_max     sunrise  \
0              8.0095           21.388970           46.800000  1469938817
1              6.4595           13.039754           29.519999  1470025324
2              6.9595           18.440998           40.320000  1470111831
3             12.3095           24.774696           52.560000  1470198340
4             11.9095           22.702845           46.800000  1470284849

       sunset  daylight_duration  sunshine_duration  precipitation_sum  \
0  1469996394          57578.500          47497.074                0.1
1  1470082680          57357.510          53008.547                0.4
2  1470168964          57134.734          19141.848                3.3
3  1470255246          56908.400          30695.604               14.0
4  1470341525          56678.450          41774.367                1.1

   rain_sum  snowfall_sum  precipitation_hours         country
0       0.1           0.0                  1.0  United Kingdom
1       0.4           0.0                  3.0  United Kingdom
2       3.3           0.0                  8.0  United Kingdom
3      14.0           0.0                 19.0  United Kingdom
4       1.1           0.0                  8.0  United Kingdom
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'sunrise', 'sunset', 'daylight_duration', 'sunshine_duration',
       'precipitation_sum', 'rain_sum', 'snowfall_sum', 'precipitation_hours',
       'country'],
      dtype='object')

In [8]:
df_canada = pd.read_csv("../data/raw/weather_data_canada.csv")
df_canada['country'] = "Canada"
print(df_canada.head())
print(df_canada.columns)
df_canada.to_csv("../data/processed/canada_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            17.723500           20.623500
1  2016-08-01 00:00:00+00:00            15.781834           19.123500
2  2016-08-02 00:00:00+00:00            15.361000           18.573502
3  2016-08-03 00:00:00+00:00            15.946416           20.773500
4  2016-08-04 00:00:00+00:00            16.123500           20.623500

   temperature_2m_min  wind_speed_10m_max  wind_gusts_10m_max     sunrise  \
0           15.923500           12.429127           30.239998  1469963304
1           14.323500           26.242987           51.120000  1470049815
2           13.773499           24.640942           57.600000  1470136327
3           12.273499           15.307410           51.120000  1470222840
4           10.773499           14.471821           35.640000  1470309354

       sunset  daylight_duration  sunshine_duration  precipitation_sum  \
0  1470021276          58039.254          20638.736               34.9
1  1470107557          57809.570          10994.917               16.2
2  1470193836          57578.105          13668.797                6.1
3  1470280113          57343.020          47178.008                0.3
4  1470366387          57104.273          56173.420                0.0

   rain_sum  snowfall_sum  precipitation_hours country
0      34.9           0.0                 24.0  Canada
1      16.2           0.0                 18.0  Canada
2       6.1           0.0                 18.0  Canada
3       0.3           0.0                  1.0  Canada
4       0.0           0.0                  0.0  Canada
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'sunrise', 'sunset', 'daylight_duration', 'sunshine_duration',
       'precipitation_sum', 'rain_sum', 'snowfall_sum', 'precipitation_hours',
       'country'],
      dtype='object')

In [9]:
df_vietnam = pd.read_csv("../data/raw/weather_data_vietnam.csv")
df_vietnam['country'] = "Vietnam"
print(df_vietnam.head())
print(df_vietnam.columns)
df_vietnam.to_csv("../data/processed/vietnam_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            23.718916              29.621
1  2016-08-01 00:00:00+00:00            23.893919              28.771
2  2016-08-02 00:00:00+00:00            23.966835              28.121
3  2016-08-03 00:00:00+00:00            23.135588              25.921
4  2016-08-04 00:00:00+00:00            23.639755              27.471

   temperature_2m_min  wind_speed_10m_max  wind_gusts_10m_max     sunrise  \
0              20.121           12.964998           34.200000  1469917847
1              20.971           13.570615           38.519997  1470004261
2              21.471           17.771753           46.800000  1470090674
3              21.671           15.856356           37.800000  1470177086
4              21.521           15.905319           40.680000  1470263498

       sunset  daylight_duration  sunshine_duration  precipitation_sum  \
0  1469963748          45891.870          43200.000                5.2
1  1470050128          45857.990          42665.650                4.9
2  1470136507          45823.690          37534.363                2.8
3  1470222884          45788.695          22924.367                2.2
4  1470309261          45752.990          29179.490                4.9

   rain_sum  snowfall_sum  precipitation_hours  country
0       5.2           0.0                  9.0  Vietnam
1       4.9           0.0                  6.0  Vietnam
2       2.8           0.0                 10.0  Vietnam
3       2.2           0.0                 11.0  Vietnam
4       4.9           0.0                  8.0  Vietnam
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'sunrise', 'sunset', 'daylight_duration', 'sunshine_duration',
       'precipitation_sum', 'rain_sum', 'snowfall_sum', 'precipitation_hours',
       'country'],
      dtype='object')

In [10]:
df_thailand = pd.read_csv("../data/raw/weather_data_thailand.csv")
df_thailand['country'] = "Thailand"
print(df_thailand.head())
print(df_thailand.columns)
df_thailand.to_csv("../data/processed/thailand_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            27.371414              31.286
1  2016-08-01 00:00:00+00:00            27.590164              30.636
2  2016-08-02 00:00:00+00:00            26.998499              29.736
3  2016-08-03 00:00:00+00:00            26.838081              30.536
4  2016-08-04 00:00:00+00:00            27.231829              30.886

   temperature_2m_min  wind_speed_10m_max  precipitation_sum   rain_sum  \
0           24.536000            9.904906           2.000000   2.000000
1           24.636000           11.013882           9.200000   9.200000
2           24.685999           11.525623           5.500000   5.500000
3           24.335999           11.570515          15.899999  15.899999
4           24.685999           10.972620          24.200003  24.200003

   snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0           0.0                  5.0           35.640000          46192.094
1           0.0                 12.0           29.160000          46153.816
2           0.0                  9.0           32.760002          46115.055
3           0.0                 11.0           32.760002          46075.510
4           0.0                 13.0           34.560000          46035.168

   sunshine_duration      sunset     sunrise   country
0          39160.312  1469965651  1469919449  Thailand
1          45326.360  1470052029  1470005865  Thailand
2          41971.610  1470138405  1470092280  Thailand
3          34842.703  1470224781  1470178695  Thailand
4          39448.445  1470311155  1470265109  Thailand
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')

In [11]:
df_japan = pd.read_csv("../data/raw/weather_data_japan.csv")
df_japan['country'] = "Japan"
print(df_japan.head())
print(df_japan.columns)
df_japan.to_csv("../data/processed/japan_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            21.870169           26.353500
1  2016-08-01 00:00:00+00:00            21.622252           26.453499
2  2016-08-02 00:00:00+00:00            20.863916           24.703499
3  2016-08-03 00:00:00+00:00            21.534746           24.753500
4  2016-08-04 00:00:00+00:00            22.159750           26.553500

   temperature_2m_min  wind_speed_10m_max  precipitation_sum   rain_sum  \
0           17.803500            5.904439           0.200000   0.200000
1           17.953499            6.162207          14.700002  14.700002
2           17.603500            5.771239          10.300000  10.300000
3           17.653500            4.452954           1.100000   1.100000
4           17.653500            5.506941           2.900000   2.900000

   snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0           0.0                  2.0           23.400000          50381.824
1           0.0                 12.0           29.160000          50281.074
2           0.0                 11.0           23.039999          50179.145
3           0.0                  3.0           18.000000          50075.220
4           0.0                  6.0           21.240000          49969.266

   sunshine_duration      sunset     sunrise country
0          47904.950  1469958819  1469908400   Japan
1          41034.074  1470045165  1469994846   Japan
2          36184.516  1470131511  1470081293   Japan
3          46757.742  1470217854  1470167740   Japan
4          40430.754  1470304196  1470254187   Japan
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')

In [12]:
df_germany = pd.read_csv("../data/raw/weather_data_germany.csv")
df_germany['country'] = 'Germany'
print(df_germany.head())
print(df_germany.columns)
df_germany.to_csv("../data/processed/germany_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            18.439915           21.942000
1  2016-08-01 00:00:00+00:00            16.937834           20.592000
2  2016-08-02 00:00:00+00:00            16.252417           18.991999
3  2016-08-03 00:00:00+00:00            17.498250           18.741999
4  2016-08-04 00:00:00+00:00            19.002417           21.592000

   temperature_2m_min  wind_speed_10m_max  precipitation_sum  rain_sum  \
0           14.392000           18.892282                0.7       0.7
1           13.642000           15.683776                0.2       0.2
2           13.992001           16.873980                2.0       2.0
3           16.292000           21.674870               10.0      10.0
4           16.142000           19.008545                4.5       4.5

   snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0           0.0                  3.0               35.64          55408.570
1           0.0                  1.0               35.64          55226.574
2           0.0                  8.0               42.48          55042.844
3           0.0                 16.0               43.92          54855.902
4           0.0                  8.0               49.68          54665.710

   sunshine_duration      sunset     sunrise  country
0          43691.430  1469991966  1469936552  Germany
1          50582.320  1470078272  1470023040  Germany
2          10556.006  1470164576  1470109527  Germany
3              0.000  1470250877  1470196016  Germany
4          18223.945  1470337176  1470282505  Germany
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')

In [13]:
df_brazil = pd.read_csv("../data/raw/weather_data_brazil.csv")
df_brazil["country"] = "Brazil"
print(df_brazil.head())
print(df_brazil.columns)
df_brazil.to_csv("../data/processed/brazil_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            27.056084           32.691500
1  2016-08-01 00:00:00+00:00            26.764420           32.741500
2  2016-08-02 00:00:00+00:00            26.749834           32.991500
3  2016-08-03 00:00:00+00:00            27.037333           33.691500
4  2016-08-04 00:00:00+00:00            27.620668           34.641502

   temperature_2m_min  wind_speed_10m_max  precipitation_sum  rain_sum  \
0             21.4415           16.610792                0.0       0.0
1             20.1415           11.183201                0.0       0.0
2             20.7915            9.007196                0.0       0.0
3             20.6415            8.825508                0.0       0.0
4             20.7915            7.594207                0.0       0.0

   snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0           0.0                  0.0           38.519997          41355.508
1           0.0                  0.0           28.440000          41388.426
2           0.0                  0.0           22.319998          41421.766
3           0.0                  0.0           21.960000          41455.810
4           0.0                  0.0           19.080000          41490.560

   sunshine_duration      sunset     sunrise country
0            39600.0  1469999916  1469958556  Brazil
1            39600.0  1470086329  1470044936  Brazil
2            39600.0  1470172742  1470131315  Brazil
3            39600.0  1470259153  1470217693  Brazil
4            39600.0  1470345565  1470304069  Brazil
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')

In [15]:
df_turkey = pd.read_csv("../data/raw/weather_data_turkey.csv")
df_turkey['country'] = "Turkey"
print(df_turkey.head())
print(df_turkey.columns)
df_turkey.to_csv("../data/processed/turkey_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            23.045248           29.576500
1  2016-08-01 00:00:00+00:00            23.295248           30.176498
2  2016-08-02 00:00:00+00:00            25.299416           32.726498
3  2016-08-03 00:00:00+00:00            26.513998           33.626500
4  2016-08-04 00:00:00+00:00            25.293165           32.376500

   temperature_2m_min  wind_speed_10m_max  wind_gusts_10m_max     sunrise  \
0             15.0765           16.595179               34.56  1469932756
1             14.8765           11.720751               29.16  1470019208
2             15.4265           12.768586               33.12  1470105660
3             16.1265           21.707731               40.68  1470192113
4             17.7265           20.608230               35.64  1470278566

       sunset  daylight_duration  sunshine_duration  precipitation_sum  \
0  1469983880          51113.600          49581.170                0.0
1  1470070221          51001.590          49522.004                0.0
2  1470156560          50888.297          49461.414                0.0
3  1470242897          50772.810          48018.664                0.0
4  1470329233          50655.090          45662.582                1.2

   rain_sum  snowfall_sum  precipitation_hours country
0       0.0           0.0                  0.0  Turkey
1       0.0           0.0                  0.0  Turkey
2       0.0           0.0                  0.0  Turkey
3       0.0           0.0                  0.0  Turkey
4       1.2           0.0                  2.0  Turkey
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'sunrise', 'sunset', 'daylight_duration', 'sunshine_duration',
       'precipitation_sum', 'rain_sum', 'snowfall_sum', 'precipitation_hours',
       'country'],
      dtype='object')

In [16]:
df_usa = pd.read_csv("../data/raw/weather_data_usa.csv")
df_usa['country'] = 'United States'
print(df_usa.head())
print(df_usa.columns)
df_usa.to_csv("../data/processed/usa_clean.csv", index=False)

                        date  temperature_2m_mean  temperature_2m_max  \
0  2016-07-31 00:00:00+00:00            28.364664           34.698000
1  2016-08-01 00:00:00+00:00            29.968832           34.398003
2  2016-08-02 00:00:00+00:00            30.804250           35.798000
3  2016-08-03 00:00:00+00:00            30.327170           35.898003
4  2016-08-04 00:00:00+00:00            30.929247           35.948000

   temperature_2m_min  wind_speed_10m_max  precipitation_sum  rain_sum  \
0              24.548           18.947083                0.0       0.0
1              26.248           19.296133                0.7       0.7
2              26.498           17.238699                0.0       0.0
3              26.048           13.202726                1.3       1.3
4              26.698           14.934577                0.5       0.5

   snowfall_sum  precipitation_hours  wind_gusts_10m_max  daylight_duration  \
0           0.0                  0.0               43.92          50600.600
1           0.0                  3.0               37.44          50496.496
2           0.0                  0.0               34.56          50391.180
3           0.0                  4.0               28.80          50283.812
4           0.0                  1.0               39.96          50174.360

   sunshine_duration      sunset     sunrise        country
0          45853.930  1470015035  1469964462  United States
1          46910.390  1470101379  1470050911  United States
2          44897.082  1470187722  1470137359  United States
3          43803.438  1470274063  1470223808  United States
4          46976.887  1470360402  1470310257  United States
Index(['date', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'wind_speed_10m_max', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_gusts_10m_max',
       'daylight_duration', 'sunshine_duration', 'sunset', 'sunrise',
       'country'],
      dtype='object')

In [2]:

usa_clean = pd.read_csv("../data/processed/usa_clean.csv")
germany_clean = pd.read_csv("../data/processed/germany_clean.csv")
brazil_clean = pd.read_csv("../data/processed/brazil_clean.csv")
turkey_clean = pd.read_csv("../data/processed/turkey_clean.csv")
thailand_clean = pd.read_csv("../data/processed/thailand_clean.csv")
uk_clean = pd.read_csv("../data/processed/uk_clean.csv")
canada_clean = pd.read_csv("../data/processed/canada_clean.csv")
india_clean = pd.read_csv("../data/processed/india_clean.csv")
vietnam_clean = pd.read_csv("../data/processed/vietnam_clean.csv")
japan_clean = pd.read_csv("../data/processed/japan_clean.csv")

In [3]:
dfs = [usa_clean, germany_clean, brazil_clean, turkey_clean, thailand_clean,
       uk_clean, canada_clean, india_clean, vietnam_clean, japan_clean]

df_all = pd.concat(dfs, ignore_index=True)

In [4]:
df_all.head()

,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,wind_speed_10m_max,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_gusts_10m_max,daylight_duration,sunshine_duration,sunset,sunrise,country
0,2016-07-31 00:00:00+00:00,28.364664,34.698000,24.548,18.947083,0.0,0.0,0.0,0.0,43.92,50600.600,45853.930,1470015035,1469964462,United States
1,2016-08-01 00:00:00+00:00,29.968832,34.398003,26.248,19.296133,0.7,0.7,0.0,3.0,37.44,50496.496,46910.390,1470101379,1470050911,United States
2,2016-08-02 00:00:00+00:00,30.804250,35.798000,26.498,17.238699,0.0,0.0,0.0,0.0,34.56,50391.180,44897.082,1470187722,1470137359,United States
3,2016-08-03 00:00:00+00:00,30.327170,35.898003,26.048,13.202726,1.3,1.3,0.0,4.0,28.80,50283.812,43803.438,1470274063,1470223808,United States
4,2016-08-04 00:00:00+00:00,30.929247,35.948000,26.698,14.934577,0.5,0.5,0.0,1.0,39.96,50174.360,46976.887,1470360402,1470310257,United States

In [5]:
df_all['country'].unique()

<StringArray>
[ 'United States',        'Germany',         'Brazil',         'Turkey',
       'Thailand', 'United Kingdom',         'Canada',          'India',
        'Vietnam',          'Japan']
Length: 10, dtype: str

In [6]:
df_all['date'] = pd.to_datetime(df_all['date'])

In [7]:
df_all['date'] = df_all['date'].dt.tz_localize(None)

In [8]:
df_all

,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,wind_speed_10m_max,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_gusts_10m_max,daylight_duration,sunshine_duration,sunset,sunrise,country
0,2016-07-31,28.364664,34.698000,24.548000,18.947083,0.000000,0.000000,0.0,0.0,43.920000,50600.600,45853.930,1470015035,1469964462,United States
1,2016-08-01,29.968832,34.398003,26.248000,19.296133,0.700000,0.700000,0.0,3.0,37.440000,50496.496,46910.390,1470101379,1470050911,United States
2,2016-08-02,30.804250,35.798000,26.498000,17.238699,0.000000,0.000000,0.0,0.0,34.560000,50391.180,44897.082,1470187722,1470137359,United States
3,2016-08-03,30.327170,35.898003,26.048000,13.202726,1.300000,1.300000,0.0,4.0,28.800000,50283.812,43803.438,1470274063,1470223808,United States
4,2016-08-04,30.929247,35.948000,26.698000,14.934577,0.500000,0.500000,0.0,1.0,39.960000,50174.360,46976.887,1470360402,1470310257,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3665,2017-07-28,22.054419,25.869000,19.869000,9.366919,11.200000,11.200000,0.0,15.0,27.359999,50705.920,32400.000,1501235789,1501185048,Japan
3666,2017-07-29,20.485666,23.269001,18.519001,9.470120,17.100000,17.100000,0.0,19.0,27.000000,50610.330,10648.941,1501322139,1501271493,Japan
3667,2017-07-30,20.862751,23.469000,18.769001,9.114471,1.300000,1.300000,0.0,9.0,30.599998,50512.457,33077.270,1501408488,1501357939,Japan
3668,2017-07-31,22.558584,26.569000,19.569000,7.421590,11.599999,11.599999,0.0,15.0,29.880000,50412.450,33455.380,1501494836,1501444386,Japan
3669,2017-08-01,19.835669,22.069000,18.019001,9.366919,7.300000,7.300000,0.0,8.0,29.519999,50310.420,8455.773,1501581181,1501530833,Japan

In [9]:
df_all.isnull().sum()

date                   0
temperature_2m_mean    0
temperature_2m_max     0
temperature_2m_min     0
wind_speed_10m_max     0
precipitation_sum      0
rain_sum               0
snowfall_sum           0
precipitation_hours    0
wind_gusts_10m_max     0
daylight_duration      0
sunshine_duration      0
sunset                 0
sunrise                0
country                0
dtype: int64

In [10]:
df_all = df_all.rename(columns={
    'temperature_2m_mean': 'temp_mean',
    'temperature_2m_max': 'temp_max',
    'temperature_2m_min': 'temp_min',
    'wind_speed_10m_max': 'wind_speed',
    'precipitation_sum': 'precipitation',
    'rain_sum': 'rain',
    'snowfall_sum': 'snow',
    'precipitation_hours': 'precip_hours',
    'wind_gusts_10m_max': 'wind_gusts'
})

In [11]:
df_all.head()

,date,temp_mean,temp_max,temp_min,wind_speed,precipitation,rain,snow,precip_hours,wind_gusts,daylight_duration,sunshine_duration,sunset,sunrise,country
0,2016-07-31,28.364664,34.698000,24.548,18.947083,0.0,0.0,0.0,0.0,43.92,50600.600,45853.930,1470015035,1469964462,United States
1,2016-08-01,29.968832,34.398003,26.248,19.296133,0.7,0.7,0.0,3.0,37.44,50496.496,46910.390,1470101379,1470050911,United States
2,2016-08-02,30.804250,35.798000,26.498,17.238699,0.0,0.0,0.0,0.0,34.56,50391.180,44897.082,1470187722,1470137359,United States
3,2016-08-03,30.327170,35.898003,26.048,13.202726,1.3,1.3,0.0,4.0,28.80,50283.812,43803.438,1470274063,1470223808,United States
4,2016-08-04,30.929247,35.948000,26.698,14.934577,0.5,0.5,0.0,1.0,39.96,50174.360,46976.887,1470360402,1470310257,United States

In [12]:
print(df_all.duplicated().sum())

0

In [13]:
df_all = df_all.reset_index(drop=True)

In [14]:
df_all.head(10)

,date,temp_mean,temp_max,temp_min,wind_speed,precipitation,rain,snow,precip_hours,wind_gusts,daylight_duration,sunshine_duration,sunset,sunrise,country
0,2016-07-31,28.364664,34.698000,24.548,18.947083,0.000000,0.000000,0.0,0.0,43.920000,50600.600,45853.930,1470015035,1469964462,United States
1,2016-08-01,29.968832,34.398003,26.248,19.296133,0.700000,0.700000,0.0,3.0,37.440000,50496.496,46910.390,1470101379,1470050911,United States
2,2016-08-02,30.804250,35.798000,26.498,17.238699,0.000000,0.000000,0.0,0.0,34.560000,50391.180,44897.082,1470187722,1470137359,United States
3,2016-08-03,30.327170,35.898003,26.048,13.202726,1.300000,1.300000,0.0,4.0,28.800000,50283.812,43803.438,1470274063,1470223808,United States
4,2016-08-04,30.929247,35.948000,26.698,14.934577,0.500000,0.500000,0.0,1.0,39.960000,50174.360,46976.887,1470360402,1470310257,United States
5,2016-08-05,29.956335,34.748000,26.248,9.826088,0.300000,0.300000,0.0,1.0,24.119999,50062.934,46800.000,1470446739,1470396706,United States
6,2016-08-06,26.779251,30.698000,24.098,11.013882,4.100000,4.100000,0.0,7.0,36.360000,49949.676,44495.992,1470533075,1470483156,United States
7,2016-08-07,26.864664,31.948000,23.548,13.276144,3.400000,3.400000,0.0,5.0,32.760002,49834.690,41514.800,1470619409,1470569606,United States
8,2016-08-08,26.079248,30.198000,22.898,14.021525,21.599998,21.599998,0.0,4.0,38.519997,49718.105,36196.074,1470705743,1470656056,United States
9,2016-08-09,28.100082,33.148003,24.648,13.493999,1.000000,1.000000,0.0,3.0,26.280000,49600.040,46800.000,1470792074,1470742506,United States

In [15]:
df_all.dtypes

date                 datetime64[us]
temp_mean                   float64
temp_max                    float64
temp_min                    float64
wind_speed                  float64
precipitation               float64
rain                        float64
snow                        float64
precip_hours                float64
wind_gusts                  float64
daylight_duration           float64
sunshine_duration           float64
sunset                        int64
sunrise                       int64
country                         str
dtype: object

In [16]:
df_all[['temp_mean', 'temp_max', 'temp_min', 'wind_speed', 'precipitation', 'rain', 'wind_gusts']] = df_all[['temp_mean', 'temp_max', 'temp_min', 'wind_speed', 'precipitation', 'rain', 'wind_gusts']].round(1)

In [17]:
df_all['sunshine_hours'] = df_all['sunshine_duration'] / 3600
df_all['daylight_hours'] = df_all['daylight_duration'] / 3600

In [18]:
df_all = df_all.drop(['sunshine_duration', 'daylight_duration'], axis=1)

In [19]:
df_all[['sunshine_hours', 'daylight_hours']] = df_all[['sunshine_hours', 'daylight_hours']].round(1)

In [20]:
df_all = df_all.drop(['sunset', 'sunrise'], axis=1)

In [21]:
df_all.head()

,date,temp_mean,temp_max,temp_min,wind_speed,precipitation,rain,snow,precip_hours,wind_gusts,country,sunshine_hours,daylight_hours
0,2016-07-31,28.4,34.7,24.5,18.9,0.0,0.0,0.0,0.0,43.9,United States,12.7,14.1
1,2016-08-01,30.0,34.4,26.2,19.3,0.7,0.7,0.0,3.0,37.4,United States,13.0,14.0
2,2016-08-02,30.8,35.8,26.5,17.2,0.0,0.0,0.0,0.0,34.6,United States,12.5,14.0
3,2016-08-03,30.3,35.9,26.0,13.2,1.3,1.3,0.0,4.0,28.8,United States,12.2,14.0
4,2016-08-04,30.9,35.9,26.7,14.9,0.5,0.5,0.0,1.0,40.0,United States,13.0,13.9

https://open-meteo.com/en/docs/historical-weather-api?utm_source=chatgpt.com&latitude=56.1304&longitude=-106.3468&start_date=2016-07-31&end_date=2017-08-01&hourly=&daily=temperature_2m_mean,temperature_2m_max,temperature_2m_min,wind_speed_10m_max,wind_gusts_10m_max,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours

In [22]:
df_all.to_csv("../data/processed/weather_countries_clean.csv", index=False)

In [23]:
df_all.groupby(['date', 'country']).size().sort_values(ascending=False).head()

date        country
2016-07-31  Brazil     1
            Canada     1
            Germany    1
            India      1
            Japan      1
dtype: int64